sudo: required
services:
  - docker

before_install:
  - docker build -t react_app -f Dockerfile.dev .

script:
  - docker run -e CI=true react_app npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south"
  app: "react_app"
  env: "Reactapp-env-1 "
  bucket_name: "elasticbeanstalk-ap-south-1-534613101025"
  bucket_path: "react_app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
